env:
  global:
    - CC_TEST_REPORTER_ID=118f05d9d9e5c1df42b52d2d973db299c8c1de12e7c2dcd24d5f992e22cfaafa
language: java
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - ./install-dependencies.sh
  - ./cc-test-reporter before-build

scala:
  - 2.12.7
script:
  - mvn -Pintegration clean test scoverage:report
after_success:
  - mvn coveralls:report
  - ./cc-test-reporter format-coverage -t cobertura target/cobertura.xml
  - ./cc-test-reporter upload-coverage
cache:
  directories:
    - $HOME/.m2
