env:
  global:
    - CC_TEST_REPORTER_ID=118f05d9d9e5c1df42b52d2d973db299c8c1de12e7c2dcd24d5f992e22cfaafa
    - PGPORT=5432
language: java
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_script:
  - ./ci-install-dependencies.sh
  - ./cc-test-reporter before-build
before_install:
  - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
  - sudo service postgresql stop 9.4
  - sudo service postgresql stop 9.5
  - sudo service postgresql stop 9.6
  - sudo service postgresql start 10
scala:
  - 2.12.7
script:
  - mvn -Pintegration clean test scoverage:report
after_success:
  - mvn coveralls:report
  - ./cc-test-reporter format-coverage -t cobertura target/cobertura.xml
  - ./cc-test-reporter upload-coverage
cache:
  directories:
    - $HOME/.m2