language: java
services:
  - postgresql
before_script:
  - psql -U postgres < src/main/resources/sql/bootstrap.sql
scala:
  - 2.12.7
script:
  - ./install-dependencies.sh
  - mvn clean test jacoco:report
after_success:
  - mvn coveralls:report
cache:
  directories:
    - $HOME/.m2
