CREATE DATABASE smough;
-- change this, obviously.
CREATE USER smough WITH ENCRYPTED PASSWORD 'smough';
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO smough;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO smough;
GRANT ALL PRIVILEGES ON DATABASE smough TO smough;