/*
 * This file is generated by jOOQ.
 */
package io.dja.smough.database;


import io.dja.smough.database.tables.Category;
import io.dja.smough.database.tables.FlywaySchemaHistory;
import io.dja.smough.database.tables.Post;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CATEGORY_NAME = Indexes0.CATEGORY_NAME;
    public static final Index CATEGORY_PKEY = Indexes0.CATEGORY_PKEY;
    public static final Index FLYWAY_SCHEMA_HISTORY_PK = Indexes0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_S_IDX;
    public static final Index POST_CREATED_ON = Indexes0.POST_CREATED_ON;
    public static final Index POST_PKEY = Indexes0.POST_PKEY;
    public static final Index POST_SLUG = Indexes0.POST_SLUG;
    public static final Index POST_UPDATED_ON = Indexes0.POST_UPDATED_ON;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CATEGORY_NAME = Internal.createIndex("category_name", Category.CATEGORY, new OrderField[] { Category.CATEGORY.NAME }, false);
        public static Index CATEGORY_PKEY = Internal.createIndex("category_pkey", Category.CATEGORY, new OrderField[] { Category.CATEGORY.ID }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_PK = Internal.createIndex("flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
        public static Index POST_CREATED_ON = Internal.createIndex("post_created_on", Post.POST, new OrderField[] { Post.POST.CREATED_ON.desc() }, false);
        public static Index POST_PKEY = Internal.createIndex("post_pkey", Post.POST, new OrderField[] { Post.POST.ID }, true);
        public static Index POST_SLUG = Internal.createIndex("post_slug", Post.POST, new OrderField[] { Post.POST.SLUG }, true);
        public static Index POST_UPDATED_ON = Internal.createIndex("post_updated_on", Post.POST, new OrderField[] { Post.POST.UPDATED_ON.desc() }, false);
    }
}
