/*
 * This file is generated by jOOQ.
 */
package io.dja.smough.database;


import io.dja.smough.database.tables.Category;
import io.dja.smough.database.tables.FlywaySchemaHistory;
import io.dja.smough.database.tables.Post;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.category</code>.
     */
    public static final Category CATEGORY = io.dja.smough.database.tables.Category.CATEGORY;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = io.dja.smough.database.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.post</code>.
     */
    public static final Post POST = io.dja.smough.database.tables.Post.POST;
}
