/*
 * This file is generated by jOOQ.
 */
package io.dja.smough.database.tables.records;


import io.dja.smough.database.tables.Post;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostRecord extends UpdatableRecordImpl<PostRecord> implements Record10<Integer, Integer, String, String, Integer, String, Timestamp, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 347404866;

    /**
     * Setter for <code>public.post.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.post.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.post.parent</code>.
     */
    public void setParent(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.post.parent</code>.
     */
    public Integer getParent() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.post.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.post.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.post.body</code>.
     */
    public void setBody(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.post.body</code>.
     */
    public String getBody() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.post.author</code>.
     */
    public void setAuthor(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.post.author</code>.
     */
    public Integer getAuthor() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.post.slug</code>.
     */
    public void setSlug(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.post.slug</code>.
     */
    public String getSlug() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.post.published_on</code>.
     */
    public void setPublishedOn(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.post.published_on</code>.
     */
    public Timestamp getPublishedOn() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.post.category</code>.
     */
    public void setCategory(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.post.category</code>.
     */
    public Integer getCategory() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.post.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.post.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>public.post.updated_on</code>.
     */
    public void setUpdatedOn(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.post.updated_on</code>.
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, String, String, Integer, String, Timestamp, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, String, String, Integer, String, Timestamp, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Post.POST.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Post.POST.PARENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Post.POST.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Post.POST.BODY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Post.POST.AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Post.POST.SLUG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Post.POST.PUBLISHED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Post.POST.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Post.POST.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Post.POST.UPDATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getParent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getBody();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getPublishedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getParent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getBody();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSlug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getPublishedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value2(Integer value) {
        setParent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value3(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value4(String value) {
        setBody(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value5(Integer value) {
        setAuthor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value6(String value) {
        setSlug(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value7(Timestamp value) {
        setPublishedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value8(Integer value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value9(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord value10(Timestamp value) {
        setUpdatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5, String value6, Timestamp value7, Integer value8, Timestamp value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostRecord
     */
    public PostRecord() {
        super(Post.POST);
    }

    /**
     * Create a detached, initialised PostRecord
     */
    public PostRecord(Integer id, Integer parent, String title, String body, Integer author, String slug, Timestamp publishedOn, Integer category, Timestamp createdOn, Timestamp updatedOn) {
        super(Post.POST);

        set(0, id);
        set(1, parent);
        set(2, title);
        set(3, body);
        set(4, author);
        set(5, slug);
        set(6, publishedOn);
        set(7, category);
        set(8, createdOn);
        set(9, updatedOn);
    }
}
